---
title: "Analysis and Modeling Exercises"
---

## AME Guidelines

We'll engage in 8 analysis and modeling exercises (AMEs). These exercises address a major goal of the course: developing skills in quantitative inference in the context biological shape.

Some specific themes we'll explore include:

* Building and applying predictive models to biological phenomena.
* Effective visualization of trends in research data.
* Qualitative and statistical inference of shape data.

Every week during the first two months of the course, we'll introduce the concepts and task taken up by each AME. These AMEs are focused mainly on quantitative approaches to shape research.

## Submissions

AMEs will be released on **Thursday** and are due the **following Tuesday**. Each AEM will include a list of objectives with a total point value of 20 points. An interpretation section in each AEM will be worth 5 points.

AMEs are meant to be short, concise explorations of quantitative topics relevant to our experimental work. Initial submissions should should be contained in an R markdown file and follow this format:

  1. The following section headers that organize your submission.
      + Analysis: A list of objectives and the relevant analysis to address them. This section can be established from pasting the objectives put forth in AME assignment description. Each objective should be accompanied by a code chunk that meets that specific objective. This may include, among other things, loading data, implementing models, and producing illuminating visualizations. **NB:** Each code chunk must be given a name that corresponds its objective, e.g., "objective 1".

      + Interpretation: A brief statement as to what the analysis means with reference to the objectives. This should be no longer than three short sentences.
 
AME markdowns should be submitted through a commit/push to your personal github repo.

